import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [prompt, setPrompt] = useState();
  const [number, setNumber] = useState(1);
  const [size, setSize] = useState("small");

  return (
    <div className="w-screen h-screen p-10 flex justify-center">
      <Head>
        <title>AI image Geneator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 className="text-4xl text-gray-600 text-center">
            Fem-AI Image Generator
          </h1>

          <h6 className="text-sm text-gray-400 text-center">
            An app that generates images using the OpenAI image generator API
          </h6>
        </div>

        <form className="flex space-x-10">
          <div className="flex flex-col">
            <label>Describe the image you want to generate</label>
            <input
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              required
              placeholder="e.g. A cat drinking tea"
            />
          </div>

          <div className="flex flex-col">
            <label>No. of Images</label>
            <input
              type="number"
              value={number}
              onChange={(e) => setNumber(e.target.value)}
              required
              min={1}
              max={5}
            />
          </div>

          <div className="flex flex-col">
            <label>Size</label>
            <select value={size} onChange={(e) => setSize(e.target.value)}>
              <option value="small">Small</option>
              <option value="medium">Medium</option>
              <option value="large">Large</option>
            </select>
          </div>

          <button>Generate</button>
        </form>

        <div>
          
        </div>
      </main>
    </div>
  );
}
