import Head from "next/head";
import { useState } from "react";
import axios from "axios";
import DisplayImages from "../components/displayImages";

export default function Home() {
  const [prompt, setPrompt] = useState("");
  const [number, setNumber] = useState(1);
  const [size, setSize] = useState("small");
  const [images, setImages] = useState(null);

  const generateImage = async (e) => {
    e.preventDefault()
    const data = {
      prompt,
      n: number,
      size
    }

    const res = await axios.post("/api/imgGenerator", data);

    setImages(res.data.data.map((item) => item.url));
  }

  return (
    <div className="w-screen h-screen p-10 md:p-20 flex justify-center">
      <Head>
        <title>AI image Geneator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="md:w-3/4">
        <div className="mb-6">
          <h1 className="text-4xl text-gray-600 text-center">
            Fem-AI Image Generator
          </h1>

          <h6 className="text-sm text-gray-400 text-center">
            An app that generates images using the OpenAI image generator API
          </h6>
        </div>

        <form className="grid grid-cols-1 md:grid-cols-6 gap-4" onSubmit={generateImage}>
          <div className="md:col-span-3 flex flex-col">
            <label>Describe the image you want to generate</label>
            <input
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              required
              placeholder="e.g. A cat drinking tea"
              className="border border-gray-400 rounded px-2 py-1 text-gray-600"
            />
          </div>

          <div className="flex flex-col">
            <label>No. of Images</label>
            <input
              type="number"
              value={number}
              onChange={(e) => setNumber(e.target.value)}
              required
              min={1}
              max={5}
              className="border border-gray-400 rounded px-2 py-1 text-gray-600"
            />
          </div>

          <div className="flex flex-col">
            <label>Size</label>
            <select
              value={size}
              onChange={(e) => setSize(e.target.value)}
              className="border border-gray-400 rounded px-2 py-1 text-gray-600"
            >
              <option value="small">Small</option>
              <option value="medium">Medium</option>
              <option value="large">Large</option>
            </select>
          </div>

          <div className="flex items-end">
            <button className="w-full bg-gray-700 hover:bg-gray-600 text-white border border-gray-400 rounded px-2 py-1">
              Generate
            </button>
          </div>
        </form>

        <div className="mt-6">
          <DisplayImages images={images} />
        </div>
      </main>
    </div>
  );
}
